data:
  dataset:
    name: office # choices are ['office', 'officehome', 'caltech-imagenet', 'visda2017']
    n_share: 10 # number of classes to be shared
    n_source_private: 10 # number of classes in source private domain
    n_total: 31 # number of classes in total

    source: 0 # source domain index
    target: 1 # target domain index
    root_path: txt # /path/to/dataset/root
  dataloader:
    class_balance: true #
    data_workers: 3 # how many workers to use for train dataloaders
    batch_size: 16 # batch_size for source domain and target domain respectively
model:
  base_model: resnet50 # choices=['resnet50', 'vgg16']
  temp: 0.05
train:
  min_step: 10000 # minimum steps to run. run epochs until it exceeds the minStep
  lr: 0.01 # learning rate for new layers. learning rate for finetune is 1/10 of lr
  multi: 0.1
  weight_decay: 0.0005
  sgd_momentum: 0.9
  momentum: 0.00
  eta: 0.05
  log_interval: 100
  thr: 1.49
  margin: 0.5
test:
  save_interval: 500 
  test_interval: 500 # interval of two continuous test phase
  test_only: False # test a given model and exit
  resume_file: '' # model to test
  resume_file1: 'log/' # model to test
  test_feat: False
  threshold: 0.6
misc:
  #gpus: 0 # how many GPUs to be used, 0 indicates CPU only

log:
  root_dir: log # the log directory (log directory will be {root_dir}/{method}/time/)
  log_interval: 10 # steps to log scalars